/*
 * Simple To Do API
 *
 * This is a simple API for managing a TO DO List
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

import (
	"errors"
	"litesoftToDo/utils/uuid"
	"litesoftToDo/utils/validate"
)

type Task struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Completed bool `json:"completed,omitempty"`
}

func (this *Task) Validate() (err error) {
	if this == nil {
		return errors.New("can't Validate nil Task")
	}
	err = validate.NoWhiteSpace("task ID", this.Id)
	if err == nil {
		err = validate.RequiredAndNoLeadingNorMultipleInnerWhiteSpace("task Name", this.Name)
	}
	return err
}

func (this *Task) EnsureId(pUUIDsource uuid.UUIDsource) (rTaskId string, err error) {
	if len(this.Id) == 0 {
		this.Id, err = pUUIDsource()
	}
	rTaskId = this.Id
	return
}

func (this *Task) UpdateWithValidated(them *Task) {
	this.Name = them.Name
	this.Completed = them.Completed
}

func (this Task) Clone() *Task { // Note, lack of star on "this" reference cause the struct to be copied
	return &this
}
