/*
 * Simple To Do API
 *
 * API version: 1.0.0
 * Original version Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"litesoftToDo/app/healthcheck"
	"litesoftToDo/app/persistence"
	"litesoftToDo/appAPI/vs-1-0-0"
	"litesoftToDo/openAPI"
	"litesoftToDo/utils/uuid"
)

func main() {
	log.Printf("Server started v3")

	zUUIDsourceFactory := uuid.NewMock("MockUUID-", 12)
	//zUUIDsourceFactory := uuid.NewImpl()

	zPersistor := persistence.NewInMemoryPersistor(zUUIDsourceFactory.GetSource())

	zRouter := openAPI.NewRouter(
		"/aweiker/ToDo",
		healthcheck.New(zPersistor).AsHealthCheckFunction(),
		vs_1_0_0.CreateRoutes(zPersistor))

	log.Fatal(http.ListenAndServe(":8080", zRouter))
}
