/*
 * Simple To Do API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vs_1_0_0

type CompletedTask struct {

	Completed bool `json:"completed"`
}
