/*
 * Simple To Do API
 *
 * API version: 1.0.0
 * Original version Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vs_1_0_0

import (
	"litesoftToDo/openAPI"
	"litesoftToDo/app/persistence"
)

const PREFIX = "/aweiker/ToDo/"
const VERSION = "1.0.0"

func CreateRoutes(pPersistor persistence.Persistor) *openAPI.VersionedRoutes {
	zMethods := MethodsNew(pPersistor)
	return openAPI.NewVersionedRoutes(PREFIX, VERSION).
	AddGet("SearchLists", zMethods.SearchLists, /* ......... */ "/lists").
	AddRoutePost("AddList", zMethods.AddList, /* ........... */ "/lists").
	AddGet("GetList", zMethods.GetList, /* ................. */ "/list/{id}").
	AddRoutePost("AddTask", zMethods.AddTask, /* ........... */ "/list/{id}/tasks").
	AddRoutePost("CompleteTask", zMethods.CompleteTask, /* . */ "/list/{id}/task/{taskId}/complete")
}
