/*
 * Simple To Do API
 *
 * This is a simple API for managing a TO DO List
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vs_1_0_0

import "litesoftToDo/app/model"

type Task struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Completed bool `json:"completed,omitempty"`
}

func FromModelTask(src *model.Task) (dst Task) {
	if src != nil {

		dst.Id = src.Id
		dst.Name = src.Name
		dst.Completed = src.Completed

	}
	return
}

func (src *Task) ToModelTask() (dst model.Task)  {
	if src != nil {

		dst.Id = src.Id
		dst.Name = src.Name
		dst.Completed = src.Completed
	}
	return
}